######################## production configuration ####################
# The base URL of your site (required). This will be prepended to all relative URLs.
baseURL: "https://akilianalytics.co/"
googleAnalytics: "G-PXMLF8LLGM"
enableRobotsTXT: true
build:
  writeStats: true
